import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ThemeProvider from "./components/Layout/page";

import "../../node_modules/bootstrap/dist/css/bootstrap.min.css"; // only CSS import is needed

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>{children}</ThemeProvider>

        {/* jQuery CDN */}
        <Script
          src="https://code.jquery.com/jquery-3.7.1.min.js"
          integrity="sha256-3gJwYpMe3C6JVb2z8+0UjzBfV0lH/fQ775/4f/OMaC4="
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
        <Script
          src="/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
